### ISSUE TITLE
Staticly registered type converter not found

### ISSUE THREAD

**Issue by jbarr21** [aurae/retrofit-logansquare#1]
My retrofit service has the following declaration:
```Call<BasicApiV3Response> someMethodNameHere()```

In my application object's onCreate(), I register custom typeconverters:
```
    private void registerLoganSquareTypeConverters() {
        LoganSquare.registerTypeConverter(Object.class, new ObjectTypeConverter());
        LoganSquare.registerTypeConverter(BasicApiV3Response.class, new BasicApiV3ResponseTypeConverter());
    }
```
but my retrofit 2.0 response can't be converted to an object. i'm using proguard but believe i'm keeping the right classes because i'm upgrading from retrofit 1.9 that I used with LoganSquare successfully. i get the following stacktrace:
```
Caused by: java.lang.IllegalArgumentException: Unable to create converter for class [package_name].model.BasicApiV3Response

Caused by: com.bluelinelabs.logansquare.NoSuchMapperException: Class [package_name].model.BasicApiV3Response could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
     at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:172)
     at [package_name].logansquare.LoganSquareConverterFactory.mapperFor(LoganSquareConverterFactory.java:34)
     at [package_name].logansquare.LoganSquareConverterFactory.fromResponseBody(LoganSquareConverterFactory.java:41)
     at retrofit.Retrofit.responseConverter(Retrofit.java:253)
     at retrofit.MethodHandler.createResponseConverter(MethodHandler.java:55)
     	... 12 more
  Caused by: java.lang.ClassNotFoundException: [package_name].model.BasicApiV3Response$$JsonObjectMapper
     at java.lang.Class.classForName(Native Method)
     at java.lang.Class.forName(Class.java:309)
     at java.lang.Class.forName(Class.java:273)
     at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:168)
     	... 16 more
  Caused by: java.lang.ClassNotFoundException: Didn't find class "[package_name].model.BasicApiV3Response$$JsonObjectMapper" on path: DexPathList[[zip file "/data/app/[package_name]-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
     	... 20 more
 	Suppressed: java.lang.ClassNotFoundException: [package_name].model.BasicApiV3Response$$JsonObjectMapper
     at java.lang.Class.classForName(Native Method)
     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
     		... 21 more
  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by aurae** [comment]
That siunds odd. I will check out custom type converters and their integration into the Retrofit process!

**Comment by aurae** [comment]
Hmm, I can't seem to reproduce the issue. In my test cases, [I also use a custom type converter](https://github.com/aurae/retrofit-logansquare/blob/master/converter-logansquare/src/test/java/com/github/aurae/retrofit/LoganSquareConverterTest.java#L77) without any problems. I have included the converter in the annotated `@JsonField` property `typeConverter`, however I just double-checked and it also works if I `registerTypeConverter()` the converter statically.

Do you run into the same issue without applying Proguard? Do you maybe initialize Retrofit before setting up your static LoganSquare converters?

**Comment by jbarr21** [comment]
@aurae Unfortunately I can't run w/o Proguard due to being over dex limit, but I do have the following rule in my proguard rules that should keep the custom type converter, so I don't believe it to be a Proguard issue.
```
-keep class com.our.package.name.** { *; }
```

Your test case has the JSON field annotated w/ the converter name like below. Is that a requirement? 
```
@JsonField(typeConverter = CustomTypeConverter.class)
```

Because I never did that in Retrofit 1.9, but instead registered the custom type converter w/ 
```
LoganSquare.registerTypeConverter(SomeCustomType.class, new SomeCustomTypeConverter());
```

This custom type is a common response type in our app and so I would prefer not to annotate every single response with a custom converter.

**Comment by jbarr21** [comment]
In addition, my custom type is declared in the retrofit response:
```
@GET("account/{username}/settings")
Call<MyCustomResponseType> getSettings(@Path("username") String username);
```

java.lang.IllegalArgumentException: Unable to create converter for class com.my.package.name.model.MyCustomResponseType for method getSettings

**Comment by jbarr21** [comment]
I've [added a test in a fork](https://github.com/jbarr21/retrofit-logansquare/commit/7742ee2f1d64c045dc17c8da5d8fa9d6f4c9042b) of the repo that looks for the behavior that I am looking for:

**Comment by aurae** [comment]
The issue you are facing relates to a misunderstanding of LoganSquare `TypeConverter`s. The way you are setting up your test case requires `CustomImplementation` to be a class annotated with `@JsonObject`, so that a `JsonObjectMapper` is generated for it. `TypeConverters` can only be used for `@JsonField` variables within those classes. Therefore, this would not work:

```java
class CustomImplementation {
    String name;
    // (...)
}

// (...)
LoganSquare.registerTypeConverter(CustomImplementation.class, new CustomImplementationTypeConverter());
CustomImplementation impl = LoganSquare.parse("{\"name\":\"LOGAN SQUARE IS COOL\"}", CustomImplementation.class);
```

But this would:

```java
@JsonObject
class SomeWrapper {
    @JsonField
    CustomImplementation impl;
    // (...)
}

// (...)
LoganSquare.registerTypeConverter(CustomImplementation.class, new CustomImplementationTypeConverter());
SomeWrapper wrapper = LoganSquare.parse("{\"impl\":{\"name\":\"LOGAN SQUARE IS COOL\"}}", SomeWrapper.class);
CustomImplementation impl = wrapper.impl;
´``

For the same reason, you can't `LoganSquare.serialize(new Date())`, even though there is a built-in TypeConverter for Java `Date` objects. You *can* however include a field of type `Date` inside a `@JsonObject` annotated class!

If your `BasicApiV3Response` is a top-level object used for serialization, annotate it instead of using a TypeConverter!

**Comment by jbarr21** [comment]
I'm using LoganSquare with Retrofit 1.9 and a LoganSquare and this is working currently. I'm using a Retrofit 1.9 converter shown below (forgot where I got it from) but it allows me to convert a response that has a custom type as its root object without any annotations. That's kind of why I was expecting to be able to do the same here with the 2.0 converter

```
/**
 * A {@link Converter} which uses parsing and serialization provided by bluelinelabs' LoganSquare library.
 * @author aurae
 */
public class LoganSquareConverter implements Converter {

    @Override
    public Object fromBody(TypedInput body, Type type) throws ConversionException {
        try {
            // Check if the type contains a parametrized list
            if (ParameterizedType.class.isAssignableFrom(type.getClass())) {
                // Grab the actual type parameter from the parametrized list and delegate to LoganSquare
                ParameterizedType parameterized = (ParameterizedType) type;
                return LoganSquare.parseList(body.in(), (Class) parameterized.getActualTypeArguments()[0]);
            } else {
                TypeConverter typeConverter;
                try {
                    typeConverter = LoganSquare.typeConverterFor((Class) type);
                } catch (NoSuchTypeConverterException nstce) {
                    typeConverter = null;
                }

                if (typeConverter != null) {
                    JsonParser jsonParser = LoganSquare.JSON_FACTORY.createParser(body.in());
                    return typeConverter.parse(jsonParser);
                } else {
                    // Single elements get parsed immediately
                    return LoganSquare.parse(body.in(), (Class) type);
                }
            }
        } catch (Exception e) {
            throw new ConversionException(e);
        }
    }

    @SuppressWarnings("unchecked")
    @Override
    public TypedOutput toBody(Object object) {
        try {
            // Check if the type contains a parametrized list
            if (List.class.isAssignableFrom(object.getClass())) {
                // Convert the input to a list first, access the first element and serialize the list
                List<Object> list = (List<Object>) object;
                if (list.isEmpty()) {
                    return new TypedString("[]");
                } else {
                    Object firstElement = list.get(0);
                    return new TypedString(LoganSquare.serialize(list, (Class<Object>) firstElement.getClass()));
                }
            } else {
                // Serialize single elements immediately
                return new TypedString(LoganSquare.serialize(object));
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
```

**Comment by aurae** [comment]
This implementation is based on [my gist for Retrofit 1.9](https://gist.github.com/aurae/8427b93b27483763d9cb), seeing as the author tag still attributes this code to me :). However, it is a modified version which actually does perform a `TypeConverter` lookup upon deserialization. This isn't an intended application of this concept though! LoganSquare itself describes a `TypeConverter` as a mechanism *"to create a way to custom parse and serialize @JsonFields"* ([source](https://github.com/bluelinelabs/LoganSquare/blob/master/core/src/main/java/com/bluelinelabs/logansquare/typeconverters/TypeConverter.java#L8)). It is not meant to deal with top-level deserialization, and instead should be applied only to fields within `@JsonObject`s.

**Comment by jbarr21** [comment]
Fair enough, thanks for the explanation!
