### ISSUE TITLE
Update to Retrofit 2.0.0

### ISSUE THREAD

**Issue by Jawnnypoo** [aurae/retrofit-logansquare#12]
As far as I can tell, it should be a quick and easy upgrade, but it would be worthwhile to verify and then update the README to reflect this libraries compatibility with Retrofit 2.0.0. :+1:

**Comment by aurae** [comment]
Already on it. ;) It took me a little longer because, during the code review of 2.0.0's changes, I had a weird inspiration regarding #3, which I wanted to include in the new release. Version `1.4.0` of the converter now uses Retrofit 2.0.0 and provides generics support at the same time!
