### ISSUE TITLE
Add support for generics and abstract base classes

### ISSUE THREAD

**Issue by aurae** [aurae/retrofit-logansquare#3]
LoganSquare's `1.2.2` release brought support for generics and abstract base classes to the table. Both of these things have to be taken into account for the converter as well; first, check if this is supported out-of-the-box by adding new test cases, then potentially add new functionality around the converter to make this work.

**Comment by aurae** [comment]
At the moment, this seems impossible, seeing as LoganSquare requires a explicitly typed `ParameterizedType<>` upon serialization. Because of type erasure, there is no way of generalizing this concept for a `ResponseBodyConverter`.

**Comment by aurae** [comment]
I have found a way to enhance retrofit-logansquare so that it is able to deal with generics. As with LoganSquare itself, this requires some reflection as it falls back to the `ParameterizedType` approach which makes serialization & parsing of generic types possible in the first place. However, this will require an additional annotation processor, which creates Mapper objects for generic types from Retrofit annotations at compile-time.

I will put some more details in this issue after having written down the approach more concisely.

**Comment by NikoYuwono** [comment]
Actually I have question that maybe related to this issue.

I want to parse reddit's listing json that structured like this

```
{
    "kind": "Listing",
    "data": {
        "modhash": "sh7oba2uei9c693c9efd9b01a64efba1558ad167a7dfcadb7d",
        "children": [
            {
                "kind": "t3",
                "data": {
                    "domain": "self.cognac",
                    "banned_by": null,
                    "media_embed": {},
                    "subreddit": "cognac",
                   ....
                 }
            },
           ...
      }
}
```

As you can see the structure of the root JSON Object and children JSON Object is pretty similar. I can create two different entity to represent both of them, but I think there should be a way to parse something like this with using generic. Is it something like this possible to do in retrofit-logansquare?

Thank you

**Comment by aurae** [comment]
At this point, generics are not supported, because LoganSquare requires some special information about the type that it wants to serialize and parse. However, there is a way to realize this, but it requires you to create non-generic sub-classes of the generic parent.

Your setup would look like this:

```java
@JsonObject
public abstract class BaseData<T> {

	@JsonField
	String kind;

	@JsonField
	T data;
}

@JsonObject
public class ListingData extends BaseData<ListingData.Listing> {

	// Basically empty, but required because of LoganSquare's generics resolution

	@JsonObject
	public static class Listing {

		@JsonField
		String modhash;

		@JsonField
		List<ItemData> children;
	}
}

@JsonObject
public class ItemData extends BaseData<ItemData.Item> {

	// Same as above

	@JsonObject
	public static class Item {

		@JsonField
		String domain;

		@JsonField(name = "banned_by")
		String bannedBy;

		// More properties...
	}
}
```

Then, your Retrofit service API method that would return this JSON data looks like this:

```java
public interface Api {
	// ...

	@GET("what/ever")
	Call<ListingData> getListings();
}
```

I am aware that it would be much nicer if you could just set `Call<BaseData<Listing>>` as the method return type, but I don't see this working without adding another annotation processor on top of LoganSquare that creates these explicit classes.

**Comment by NikoYuwono** [comment]
Yes, that's actually a nice workaround for now. Thanks @aurae !

**Comment by aurae** [comment]
Support for generics has been added in `1.4.0´.
