### ISSUE TITLE
 JsonMapperLoaderImpl class not found. Have you included the steps needed for LoganSquare to process your annotations?

### ISSUE THREAD

**Issue by cshalysongoncalves** [aurae/retrofit-logansquare#5]
Hi,
I am using your convert to retrofit 2.0. However, I am getting a RuntimeException when retrofit attempts to parse. Any idea why?

@JsonObject
public class LoginVO implements Serializable {
    private static final long serialVersionUID = 6767821651137474070L;
    @JsonField(name = "success")
    private boolean status;
    @JsonField(name = "message")
    private String message;
    @JsonField(name = "token")
    private String token;
    @JsonField(name = "user")
    private UserVO userVO;

    public LoginVO() {
    }

    public LoginVO(boolean status, String message, String token, UserVO userVO) {
        this.status = status;
        this.message = message;
        this.token = token;
        this.userVO = userVO;
    }

    public boolean isStatus() {
        return status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public UserVO getUserVO() {
        return userVO;
    }

    public void setUserVO(UserVO userVO) {
        this.userVO = userVO;
    }
}

**Comment by aurae** [comment]
First things first, does serialization and parsing of this class work outside of the Retrofit context? Your exception hints at a misconfiguration of LoganSquare, not the converter itself.

**Comment by halysongoncalves** [comment]
I added .addConverter Factory (LoganSquareConverter Factory.create ()), compile "com.github.aurae.retrofit: convert logansquare: 1.1.0" and wrote the fields with JSONObject and JsonField. When I change to Gson, everything works normally! Any idea what could be the problem?

**Comment by aurae** [comment]
How are you pulling in the dependency on LoganSquare? As it relies on annotation processing to do its job, you need to add both the library and the processor to your build.gradle alongside the converter! Check out LoganSquare's docs forbmore of that. I will extend the readme to include some information on the configuration as well.

**Comment by halysongoncalves** [comment]
I will perform the test and I will tell you. I was thinking, if you already import dependence logan square on your converter, the user would not need to add too?

**Comment by aurae** [comment]
The library has an intrinsic dependency on LoganSquare, that's true. However, it doesn't include the annotation processing part, which is provided by external plugins (in this case, Hugo Visser's `android-apt`). Last time I checked, his plugin wasn't triggering annotation processing in transitive dependencies, which is another reason why you should add that yourself. Good catch on pointing out the need to give a hint on this in the Readme, though!
